<div class="cs-styleguide__container cs-styleguide__container--contrast">

    <div class="cs-styleguide__title">
        Badges
    </div>

    <div class="cs-styleguide__section cs-styleguide__section--columns">
        <div class="cs-multiple-badges">
            <span class="cs-badge cs-badge--label-big cs-badge--attention">
                <span class="cs-badge__span"><?= __('-10%'); ?></span>
            </span>
        </div>

        <div>
            <span class="cs-badge cs-badge--new cs-badge--label-big">
                <span class="cs-badge__span cs-badge__span--no-space"><?= __('neu'); ?></span>
            </span>
        </div>


    </div>

</div>
