<?php
/** @var \Creativestyle\FrontendExtension\Helper\Store $storeHelper */
$storeHelper = $this->helper('Creativestyle\FrontendExtension\Helper\Store');
$currentStoreId = $storeHelper->getCurrentStoreId();

?>
<?php echo $this->getLayout()
    ->createBlock('Magento\Cms\Block\Block')
    ->setCacheKey('cart_banners_'.$currentStoreId)
    ->setCacheLifetime(86400)
    ->setBlockId('cart_banners')
    ->toHtml();
?>
