<?php
/** @var \Creativestyle\FrontendExtension\Helper\Store $storeHelper */
$storeHelper = $this->helper('Creativestyle\FrontendExtension\Helper\Store');
$currentStoreId = $storeHelper->getCurrentStoreId();

?>
<div class="cs-page-bottom__column cs-page-bottom__column--logo">
    <?php echo $this->getLayout()
        ->createBlock('Magento\Cms\Block\Block')
        ->setCacheKey('pagebottom_logo_'.$currentStoreId)
        ->setCacheLifetime(86400)
        ->setBlockId('pagebottom_logo')
        ->toHtml();
    ?>
</div>

<div class="cs-page-bottom__column cs-page-bottom__column--shipping">
    <h3 class="cs-page-bottom__column-title"><?php echo __('Shippings') ?></h3>
    <div class="cs-page-bottom__list">
        <?php echo $this->getLayout()
            ->createBlock('Magento\Cms\Block\Block')
            ->setCacheKey('pagebottom_shipping_'.$currentStoreId)
            ->setCacheLifetime(86400)
            ->setBlockId('pagebottom_shipping')
            ->toHtml();
        ?>
    </div>
</div>
<div class="cs-page-bottom__column cs-page-bottom__column--payment">
    <h3 class="cs-page-bottom__column-title"><?php echo __('Payments') ?></h3>
    <div class="cs-page-bottom__list">
        <?php echo $this->getLayout()
            ->createBlock('Magento\Cms\Block\Block')
            ->setCacheKey('pagebottom_payment_'.$currentStoreId)
            ->setCacheLifetime(86400)
            ->setBlockId('pagebottom_payment')
            ->toHtml();
        ?>
    </div>
</div>
