<?php extract($block->getData()); ?>
<li class="<?php echo /* @escapeNotVerified */ $viewModeClass; ?>__brick <?php if($showHeroProduct): ?><?php echo $viewModeClass; ?>__brick--teaser <?php echo $viewModeClass; ?>__brick--x2 <?php echo $viewModeClass; ?>__brick--y2<?php endif; ?>">
    <div class="cs-grid-product <?php if($showHeroProduct): ?>cs-grid-product--hero<?php endif; ?>">
        <?php
            $productImageSrcset = $productImageUrl . ' 1x, ' . $productImageUrl2x . ' 2x';
            $productNameStripped = $block->stripTags($product->getName(), null, true);
            $getIsSalable = $salabilityStatus[$product->getId()];
            $newBadge = $badgeHelper->isNew($product);
            $newBadgeText = 'New';
            $discount = $badgeHelper->getSalePercentage($product);
            $isPopular = $indicatorsHelper->getPopularIconFlag($product->getId());
            $postParams = $block->getAddToCartPostParams($product);
            $showDetails = '';
            $productHelper = $this->helper('Creativestyle\FrontendExtension\Helper\Product');
            $addToCart = '';
            $addToCartText = __('Add to cart');
            $addToCartUrl = $productHelper->getAddToCartUrl($product->getId());
            $oldPrice = $product->getPriceInfo()->getPrice('regular_price')->getAmount()->getValue();
            $finalPrice = $product->getPriceInfo()->getPrice('final_price')->getAmount()->getValue();
            $pricingHelper = $this->helper('Magento\Framework\Pricing\Helper\Data');

            $showDetails = '<a href="'. $product->getProductUrl() .'">
                                    <button class="cs-button cs-button--type_wide">
                                        <span class="cs-button__span">' . __('Details') . '</span>
                                    </button>
                                </a>';

            $addToCart =
            '<div class="cs-grid-product__info">
                <div class="price-box"> <span class="price"> '. $pricingHelper->currency($oldPrice,true,false) . ' </span></div>
                <form data-role="tocart-form" action="' . $addToCartUrl . '" method="post">
                    <input type="hidden" name="product" value="' . $postParams['data']['product'] . '">' . $block->getBlockHtml('formkey') . '
                    <button type="submit"
                            title="' . $block->escapeHtml($addToCartText) . '"
                            class="tocart | cs-button cs-button--type_cart-short">
                        <svg class="cs-button__icon cs-button__icon--cart">
                            <use xlink:href="#cart"></use>
                        </svg>
                    </button>
                </form>
            </div>';

            if( $discount ) {
                $badges[] = [
                    'content' => '<span class="cs-badge cs-badge--discount">
                        <span class="cs-badge__span">'  . $discount . '%</span>
                    </span>'
                ];

            }

            if ( $newBadge ) {
                $badges[] = [
                    'content' => '<span class="cs-badge cs-badge--new">
                        <span class="cs-badge__span">' . __($newBadgeText) . '</span>
                    </span>'
                ];
            }

            if ( $isPopular ) {
                $badges[] = [
                    'content' => '<span class="cs-badge cs-badge--positive">
                        <span class="cs-badge__span">' . __('Popular') . '</span>
                    </span>'
                ];
            }

            $data = [
                'lazyload' => $iterator > 9,
                'url' => $product->getProductUrl(),
                'image' => [
                    'src' => $productImageUrl,
                    'srcset' => $productImageSrcset,
                    'alt' => $productNameStripped,
                    'width' => '216',
                    'height' => '270'
                ],
                'name' => $helper->productAttribute($product, $product->getName(), 'name'),
                'addons' => [
                    'bottom' => [
                        [
                            'mix' => 'cs-grid-product__addon--show-details',
                            'content' => $showDetails
                        ]
                    ]
                ],
                'hotspots' => [
                    'after' => [
                        'name' =>  $addToCart
                    ],
                ]
            ];

        ?>
        <?=$this->getLayout()->createBlock(
            'Creativestyle\FrontendExtension\Block\Twig', 'grid-product-'.$iterator, [
                'data' => $data
            ]
        )->setTemplate("grid-product/grid-product.twig")->toHtml(); ?>
    </div>
</li>
