<?php
$product = $block->getProduct();
$isNew = $this->helper('Creativestyle\FrontendExtension\Helper\Product')->isNew($product);
$discontValue = $this->helper('Creativestyle\FrontendExtension\Helper\Product')->getSalePercentage($product);


?>

<div class="cs-product-gallery__badge-wrapper">
    <?php if ($isNew): ?>
        <span class="cs-badge cs-badge--new cs-badge--label-big">
            <span class="cs-badge__span cs-badge__span--no-space"><?= __('New'); ?></span>
        </span>
    <?php endif; ?>

    <?php if ($discontValue > 0): ?>
        <span class="cs-badge cs-badge--attention cs-badge--label-big">
            <span class="cs-badge__span">-<?php echo $discontValue; ?>%</span>
        </span>
    <?php endif; ?>

    <?php echo $block->getChildHtml('popular.badge') ?>
</div>


