<?php
// @codingStandardsIgnoreFile

/**
 * @var $block \Magento\Catalog\Block\Product\View\Attributes
 */
$storeHelper = $this->helper('Creativestyle\FrontendExtension\Helper\Store');
$currentStoreId = $storeHelper->getCurrentStoreId();
$product = $block->getProduct();
$mixture = $product->getData('mixture');
$ingredients = $product->getData('ingredients');
$ghs = explode(',', $product->getGhs());
$hazardNote = $product->getData('hazard_note');
?>

<?php if(!is_null($mixture)) : ?>
    <div class="cs-hints__mixture">
        <div class="cs-headline cs-hints__headline">
            <h2 class="cs-headline__title"><?php /* @escapeNotVerified */  echo __('Mixture'); ?> </h2>
        </div>
        <div class="cs-hints__content">
            <?php echo($mixture); ?>
        </div>
    </div>
<?php endif; ?>

<?php if(!is_null($ingredients)) : ?>
    <div class="cs-hints__ingredients">
        <div class="cs-headline cs-hints__headline">
            <h2 class="cs-headline__title"><?php /* @escapeNotVerified */  echo __('Ingredients'); ?> </h2>
        </div>
        <div class="cs-hints__content">
            <?php echo($ingredients); ?>
        </div>
    </div>
<?php endif; ?>

<?php if(strlen($ghs[0]) > 0) : ?>
    <div class="cs-headline cs-warnings__headline" id="warnings-section">
        <h2 class="cs-headline__title"><?php /* @escapeNotVerified */  echo __('Warnings'); ?> </h2>
    </div>
    <div class="cs-warnings">
        <div class="cs-warnings__icons-container">
        <?php $warning = ''; ?>
        <?php foreach ($ghs as $data): ?>        
            <?php
            $warningIcon = '
                <svg class="cs-warnings__icon">
                    <use href="#ghs0' . ($data-19) . '" xlink:href="#ghs0' . ($data-19) . '">
                    </use>
                </svg>';
            $warning .= $warningIcon;
            ?>
        <?php endforeach; ?>
        <?php echo($warning); ?>
        </div>
        <?php if (trim($hazardNote)): ?>
            <div class="cs-warnings__description">
                <?php echo($hazardNote); ?>
            </div>
        <?php endif; ?>
    </div>
<?php endif; ?>
