<?php
// @codingStandardsIgnoreFile

/**
 * @var $block \Magento\Catalog\Block\Product\View\Attributes
 */
$storeHelper = $this->helper('Creativestyle\FrontendExtension\Helper\Store');
$currentStoreId = $storeHelper->getCurrentStoreId();
$product = $block->getProduct();
?>

<?php $ghs = explode(',', $product->getGhs()); ?>
<?php if(strlen($ghs[0]) > 0) : ?>
    <div class="cs-headline cs-warnings__headline" id="warnings-section">
        <h2 class="cs-headline__title"><?php /* @escapeNotVerified */  echo __('Warnings'); ?> </h2>
    </div>
    <div class="cs-warnings">
        <div class="cs-warnings__icons-container">
        <?php $warning = ''; ?>
        <?php foreach ($ghs as $data): ?>        
            <?php
            $warningIcon = '
                <svg class="cs-warnings__icon">
                    <use href="#ghs0' . ($data-19) . '" xlink:href="#ghs0' . ($data-19) . '">
                    </use>
                </svg>';
            $warning .= $warningIcon;
            ?>
        <?php endforeach; ?>
        <?php echo($warning); ?>
        </div>
        <?php if (trim($product->getData('hazard_note'))): ?>
            <div class="cs-warnings__description">
                <?php echo($product->getData('hazard_note')); ?>
            </div>
        <?php endif; ?>
    </div>

<?php endif; ?>
