<?php
// @codingStandardsIgnoreFile

/** @var $block \Magento\Customer\Block\Account\AuthorizationLink */
$dataPostParam = '';
if ($block->isLoggedIn()) {
    $dataPostParam = sprintf(" data-post='%s'", $block->getPostParams());
}
?>

<ul class="cs-information-stripe__list" data-label="<?php echo $block->escapeHtml(__('or')); ?>">
    <li class="cs-information-stripe__item cs-information-stripe__item--last cs-information-stripe__item--login | cs-list__item">
        <a
            class="cs-information-stripe__account-link"
            <?php /* @escapeNotVerified */ echo $block->getLinkAttributes(); ?>
            <?php /* @escapeNotVerified */ echo $dataPostParam; ?>
        >
            <span class="cs-information-stripe__account-label">
                <?php echo $block->escapeHtml($block->getLabel()); ?>
            </span>
            <svg class="cs-information-stripe__account-icon">
                <use xlink:href="#login"></use>
            </svg>

        </a>
    </li>
</ul>
