<?php
// @codingStandardsIgnoreFile

/* @var $block \Magento\Catalog\Block\Product\AbstractProduct */
?>

<?php
switch ($type = $block->getType()) {

    case 'related-rule':
        if ($exist = $block->hasItems()) {
            $type = 'related';
            $class = $type;

            $image = 'related_products_list';
            $title = __('Related Products');
            $items = $block->getAllItems();
            $limit = $block->getPositionLimit();
            $shuffle = (int) $block->isShuffled();
            $canItemsAddToCart = $block->canItemsAddToCart();

            $showAddTo = true;
            $showCart = false;
            $templateType = null;
            $description = false;
        }
        break;

    case 'related':
        /** @var \Magento\Catalog\Block\Product\ProductList\Related $block */
        if ($exist = $block->getItems()->getSize()) {
            $type = 'related';
            $class = $type;

            $image = 'related_products_list';
            $title = __('Related Products');
            $items = $block->getItems();
            $limit = 0;
            $shuffle = 0;
            $canItemsAddToCart = $block->canItemsAddToCart();

            $showAddTo = true;
            $showCart = false;
            $templateType = null;
            $description = false;
        }
        break;

    case 'upsell-rule':
        if ($exist = $block->hasItems()) {
            $type = 'upsell';
            $class = $type;

            $image = 'upsell_products_list';
            $title = __('You might like...');
            $items = $block->getAllItems();
            $limit = $block->getPositionLimit();
            $shuffle = (int) $block->isShuffled();

            $showAddTo = false;
            $showCart = false;
            $templateType = null;
            $description = false;
            $canItemsAddToCart = false;
        }
        break;

    case 'upsell':
        /** @var \Magento\Catalog\Block\Product\ProductList\Upsell $block */
        if ($exist = count($block->getItemCollection()->getItems())) {
            $type = 'upsell';
            $class = $type;

            $image = 'upsell_products_list';
            $title = __('You might like...');
            $items = $block->getItemCollection()->getItems();
            $limit = $block->getItemLimit('upsell');
            $shuffle = 0;

            $showAddTo = false;
            $showCart = false;
            $templateType = null;
            $description = false;
            $canItemsAddToCart = false;
        }
        break;

    case 'crosssell-rule':
        /** @var \Magento\Catalog\Block\Product\ProductList\Crosssell $block */
        if ($exist = $block->hasItems()) {
            $type = 'crosssell';
            $class = $type;

            $image = 'cart_cross_sell_products';
            $title = __('More Choices:');
            $items = $block->getItemCollection();

            $showAddTo = true;
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = false;
            $canItemsAddToCart = false;
        }
        break;

    case 'crosssell':
        /** @var \Magento\Catalog\Block\Product\ProductList\Crosssell $block */
        if ($exist = $block->getItemCount()) {
            $type = 'crosssell';
            $class = $type;

            $image = 'cart_cross_sell_products';
            $title = __('More Choices:');
            $items = $block->getItems();

            $showAddTo = true;
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = false;
            $canItemsAddToCart = false;
        }
        break;

    case 'new':
        if ($exist = $block->getProductCollection()) {
            $type = 'new';
            $mode = 'grid';
            $type = $type . ' ' . $mode;

            $class = 'widget' . ' ' . $type;

            $image = 'new_products_content_widget_grid';
            $title = __('New Products');
            $items = $exist;

            $showAddTo = true;
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = ($mode == 'list') ? true : false;
            $canItemsAddToCart = false;
        }
        break;

    case 'other':
        break;
}
?>

<?php if ($exist):?>
    <?php
    $products = [];

    $iterator = 1;
    foreach ($items as $item) {
        $csProductHelper = $this->helper('Creativestyle\FrontendExtension\Helper\Product');
        $salabilityHelper = $this->helper('Creativestyle\FrontendExtension\Helper\Product\Salability');
        $indicatorsHelper = $this->helper('Creativestyle\ProductPositiveIndicatorsExtension\Helper\Product');
        $getIsSaleable = $item->getIsSalable();
        $getId = $item->getId();
        $getAddToCartUrl = $block->getAddToCartUrl($item);
        $itemNameStripped = $block->stripTags($item->getName(), null, true);
        $newBadge = $csProductHelper->isNew($item);
        $discount = $csProductHelper->getSalePercentage($item);
        $isPopular = $indicatorsHelper->getPopularIconFlag($item->getId());
        $postParams = $block->getAddToCartPostParams($item);
        $postParams = $block->getAddToCartPostParams($item);
        $addToCartText = 'Add to Cart';
        $addToCartUrl = $csProductHelper->getAddToCartUrl($item->getId());
        $dailyDealHelper = $this->helper('Creativestyle\DailyDealExtension\Helper\OfferData');
        $dailyDealData = $dailyDealHelper->prepareOfferData($item);
        $badges = [];
        $dailyDealHtml = '';
        $ghs = explode(',', $item->getGhs());
        if (strlen($ghs[0]) > 0){
             $ghs = array_map(function ($item) { return 'ghs0' . ($item-19); }, $ghs);
        } else {
            $ghs = '';
        }

        $addToCart = '
                <form data-role="tocart-form" action="' . $addToCartUrl . '" method="post">
                    <input type="hidden" name="product" value="' . $postParams['data']['product'] . '">' . $block->getBlockHtml('formkey') . '
                    <button type="submit"
                        title="' . $block->escapeHtml($addToCartText) . '"
                        class="tocart | cs-button--type_grid-tocart">
                    </button>
                </form>';

        $data = [
            'image' => $this->helper('Magento\Catalog\Helper\Image')->init($item, $image)->getUrl(),
            'url' => $block->getProductUrl($item),
            'name' => $itemNameStripped,
            'price' => $block->getProductPrice($item),
            'getIsNewProduct' => $csProductHelper->isNew($item),
            'getSalePercentage' => $csProductHelper->getSalePercentage($item),
            'addToCartButtonHtml' => $addToCart,
            'dailyDealOffer' => $dailyDealData,
            'popularIconFlag' => $isPopular,
            'ghs' => $ghs
        ];
        
        array_push($products, $data );
        $iterator++;
    }

    ?>

    <?=$this->getLayout()->createBlock(
        'Creativestyle\FrontendExtension\Block\Twig', 'carousels-headline-'.$type, [
            'data' => [
                'title' => $title,
                'tag' => 'h2'
            ]
        ]
    )->setTemplate("headline/headline.twig")->toHtml(); ?>

    <?=$this->getLayout()->createBlock(
        'Creativestyle\FrontendExtension\Block\Twig', 'products-promo-'.$type, [
            'data' => [
                'namespace' => 'cs-',
                'showPagination' => true,
                'showNavigation' => true,
                'dataPassed' => true,
                'products' => $products,
            ]
        ]
    )->setTemplate("products-promo/products-promo.twig")->toHtml(); ?>



<?php endif;?>